<?php

namespace Sgdng\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadRepository extends EntityRepository
{
}
