sgdng_rest:
    resource: "@SgdngRestBundle/Resources/config/routing.yml"
    prefix:   /
    type:     rest

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
