parameters:
#    sgdng_rest.example.class: Sgdng\RestBundle\Example

services:
#    sgdng_rest.example:
#        class: %sgdng_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
