parameters:
#    sgdng_api.example.class: Sgdng\ApiBundle\Example

services:
#    sgdng_api.example:
#        class: %sgdng_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
